name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev g++-mingw-w64-i686

      - name: Build for Ubuntu
        run: |
          cmake -B build-ubuntu
          cmake --build build-ubuntu

      - name: Upload for Ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: GravityDefied
          path: build-ubuntu/GravityDefied

      - name: Build for Windows
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-toolchain.cmake -B build-win32
          cmake --build build-win32

      - name: Upload for Windows
        uses: actions/upload-artifact@v4
        with:
          name: GravityDefied.exe
          path: build-win32/GravityDefied.exe
